# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - run: hostnamectl
    - run: pwd
    - run: touch foobaz.txt
    - run: touch /mnt/yeah.txt
    - run: ls /mnt

  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
    - run: hostnamectl
    - run: pwd
    - run: ls /mnt
