name: pipe

on: [push]

jobs:
  _0:
    runs-on: ubuntu-latest
    steps:
      - name: loop
        continue-on-error: true 
        shell: bash
        run: |
          hostnamectl
          pwd
          mkdir -p ~/tmp
          touch ~/tmp/hello_world1.txt
          ls ~/tmp
          echo
          ls ~
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: tmp
          path: ~/tmp
  _1:
    needs: _0
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/download-artifact@v4
        with:
          name: tmp
          path: ~/tmp
      - name: loop
        continue-on-error: true 
        shell: bash
        run: |
          hostnamectl
          pwd
          touch ~/tmp/hello_world2.txt
          ls ~/tmp
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: tmp
          path: ~/tmp
  _2:
    needs: _1
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/download-artifact@v4
        with:
          name: tmp
          path: ~/tmp
      - name: loop
        continue-on-error: true 
        shell: bash
        run: |
          hostnamectl
          pwd
          touch ~/tmp/hello_world3.txt
          ls ~/tmp
          
