name: pipe

on: [push]

jobs:
  _0:
    runs-on: ubuntu-latest
    steps:
      - name: loop
        continue-on-error: true 
        shell: bash
        run: |
          hostnamectl
          echo "Setting up VM"
          pwd
          touch hello_world1.txt
          ls ~
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: tmp
          path: /home/runner
          
  _1:
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/download-artifact@v4
        with:
          name: tmp
      - name: loop
        continue-on-error: true 
        shell: bash
        run: |
          hostnamectl
          echo "Setting up VM"
          pwd
          touch hello_world2.txt
          ls ~
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: tmp
          path: /home/runner
  _2:
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/download-artifact@v4
        with:
          name: tmp
      - name: loop
        continue-on-error: true 
        shell: bash
        run: |
          hostnamectl
          echo "Setting up VM"
          pwd
          touch hello_world3.txt
          ls ~
          
