# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - run: df -ah
    - run: hostnamectl
    - run: pwd
    - run: sudo mkdir -p /mnt/mydir
    - run: sudo touch /mnt/mydir/foobar.txt
    # Cached
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          /mnt/mydir
        key: ${{ runner.os }}-build-${{ hashFiles('**/lockfiles') }} # Change the key based on your requirements

  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
    # Restore cached directories at the beginning of the job
    - name: Restore dependencies
      uses: actions/cache@v2
      with:
        path: |
          /mnt/mydir
        key: ${{ runner.os }}-build-${{ hashFiles('**/lockfiles') }} # Match the key used in the build job
    # Restored
    - run: df -ah
    - run: hostnamectl
    - run: pwd
    - run: sudo ls /mnt
    - run: sudo ls /mnt/mydir
