name: invoker

on:
  workflow_dispatch:

jobs:
  _null:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.API_KEY }}" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/neuronbuatan/mesin/actions/runs/8697049650/rerun"
